# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/repo

version: 1
jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Install pytest
          command: sudo pip install pytest
      - run:
          name: Install looker_sdk
          command: sudo pip install looker_sdk
      - run:
          name: Create package distribution
          command: python setup.py sdist
      - persist_to_workspace:
          root: dist
          paths:
            - .
      - run:
          name: Run tests
          command: python -m pytest tests/test_*.py

  pypi:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Upload package
          command: build-scripts/upload-project.sh

workflows:
  version: 2
  build-pypi:
    jobs:
      - build
      - pypi:
          requires:
            - build
          filters:
            branches:
              only: main